server:
  port: 8080

spring:
  jackson:
    mapper:
      sort-properties-alphabetically: false
  application:
    name: electro
  datasource:
    username: root
    password: minh071205
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

