server:
  port: 8080

spring:
  jackson:
    mapper:
      sort-properties-alphabetically: false
  application:
    name: electro
  datasource:
    username: root
    password: Minh071205@
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  devtools:
    restart:
      enabled: true
      poll-interval: 1000
      quiet-period: 400

